#!/usr/bin/env ruby

require 'rbender/support/telegram_bot_api_schema'

SCHEMA_PATH = 'boilerplates/config/schema/telegram_bot_api_schema.json'

RBender::Support::TelegramBotApiSchema.schema_file_path = SCHEMA_PATH
RBender::Support::TelegramBotApiSchema.new.update!
